export default {
  cyrillic: /^[а-яА-ЯЁё ]+$/,
  email: /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
  password: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{8,})/,
  phone: /^[0-9]{3}[0-9]{3}[0-9]{2}[0-9]{2}$/,
  latin: /^[a-zA-Z ]+$/,
  number: /^[0-9]+$/,
  any: /^[\s\S]+$/,
  cyrillicAndNumber: /^[а-яА-ЯЁё0-9\\.\\, ]+$/,
  latinAndNumber: /^[a-zA-Z0-9]+$/,
  passport: /^[a-zA-Z0-9]{9,11}$/,
  identityCard: /^[0-9]{9}$/,
  iin: /^[0-9]{12}$/,
  residencePermit: /^[a-zA-Z0-9]{9,14}$/,
  creationDateDocuments: /^(0[1-9]|[1-2][0-9]|3[0-1])-(0[1-9]|1[0-2])-[0-9]{4}$/,
  dateFormat: /^([0-9]{2})-([0-9]{2})-([0-9]{4})$/,
  punctuationMarks: /^(?=.*[!@#\$%\^&\*])/,
  capitalLetters: /^(?=.*[A-Z])/,
  lowerLetters: /^(?=.*[a-z])/,
  numbersAndLatin: /^(?=.*[0-9])/,
}
